# Generated by Django 5.2.6 on 2026-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_touristspot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
