# Generated by Django 5.2.6 on 2026-06-09 09:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_touristspot_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
