# Generated by Django 5.2.6 on 2026-05-12 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bhandara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_maps_url', models.URLField(max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('area_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organizer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_details', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('current_crowd_status', models.CharField(choices=[('LOW', 'Moving Fast'), ('MODERATE', 'Moderate Rush'), ('HIGH', 'Heavy Rush')], default='LOW', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_verified_owner', models.BooleanField(default=False)),
            ],
        ),
    ]
