# Generated by Django 5.2.6 on 2026-05-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhandara_radar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bhandara',
            options={'verbose_name': 'Bhandara Location', 'verbose_name_plural': 'Bhandara Locations'},
        ),
    ]
