# Generated by Django 5.2.6 on 2025-10-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_phone_on_approval',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
