# Generated by Django 5.2.6 on 2026-06-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_dailyvisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyVisit',
        ),
    ]
